import {Evidence} from "./Evidence.model";
import {Witness} from "./Witness.model";
import {WitnessPlayer} from "./WitnessPlayer.model";

export interface Case {
  _id: string;
  name: string;
  judgeName: string;
  plaintiffName: string;
  defendantName: string;
  witnessName1: string;
  witnessName2: string;
  witnessName3: string;
  witnessName4: string;
  witnessName5: string;
  selectedWitness1: Witness;
  selectedWitness2: Witness;
  selectedWitness3: Witness;
  selectedWitness4: Witness;
  selectedWitness5: Witness;
  witnessPool1: Witness[];
  witnessPool2: Witness[];
  witnessPool3: Witness[];
  witnessPool4: Witness[];
  witnessPool5: Witness[];
  issue: string;
  plaintiffEvidencePool: Evidence[];
  plaintiffEvidenceSelected: Evidence[];
  plaintiffEvidenceCourt: Evidence[];
  defendantEvidencePool: Evidence[];
  defendantEvidenceSelected: Evidence[];
  defendantEvidenceCourt: Evidence[];
  isDefendantGuilty: boolean;
  status: number;
  closedDate: string;
  openedDate: string;
  logs: string[];
  version: number;

  // attributes
  fullCaseName: string;
  areEssentialNamesSet: boolean;
  isAnyNameSet: boolean;
  howManyPlayerNames: number;
  howManyWitnessNames: number;
  judgeNameSet: boolean;
  plaintiffNameSet: boolean;
  defendantNameSet: boolean;
  witness1NameSet: boolean;
  witness2NameSet: boolean;
  witness3NameSet: boolean;
  witness4NameSet: boolean;
  witness5NameSet: boolean;
  howManyWitnessesSelected: number;
  allWitnessesReady: boolean;
  witnessPlayers: WitnessPlayer[];
  isAllEvidenceSelected: boolean;
  isAllPlaintiffEvidenceSelected: boolean;
  isAllDefendantEvidenceSelected: boolean;
  isAllEvidenceRevealed: boolean;
  isAllPlaintiffEvidenceRevealed: boolean;
  isAllDefendantEvidenceRevealed: boolean;
  statusText: string;
  isAssignRoles: boolean;
  isMakeSelections: boolean;
  isFreeTime: boolean;
  isOpeningArguments: boolean;
  isCrossfire: boolean;
  isClosingArguments: boolean;
  isVerdictSelection: boolean;
  isClosed: boolean;
  isInProgress: boolean;
  verdictIsNext: boolean;
  lastStatusUpdateDate: string;
}
