export const enum ROUTES_ENUM {
  Dashboard = "dashboard",
  Info = "info",
  Profile = "profile",
  Admin = "admin",
  CourtRoom = "courtroom",
  Judge = "judge",
  Plaintiff = "plaintiff",
  Defendant = "defendant",
  Witness = "witness",
  Jury = "jury",
  RoleSelect = "role-select",
  EvidenceOverview = "evidence-overview",
  EvidenceDetails = "evidence-details",
  EvidenceForm = "evidence-form",
  WitnessOverview = "witness-overview",
  WitnessDetails = "witness-details",
  WitnessForm = "witness-form",
  IssueOverview = "issue-overview",
  IssueDetails = "issue-details",
  IssueForm = "issue-form",
  CaseOverview = "case-overview",
  CaseDetails = "case-details",
  CaseBuilder = "case-builder",
  UserOverview = "user-overview",
  Login = "login",
}
